title: Festus Aigbogun 
#logo: /assets/img/headshot_circle.png
description: Hello, I am a dedicated data analyst with a year of hands-on experience in SQL, PowerBI, Tableau, and Microsoft Excel. I leverage these tools to meticulously analyze complex datasets, derive actionable insights, and present compelling visualizations. My expertise lies in transforming raw data into meaningful narratives, enabling informed decision-making for organizations. I bring a combination of technical proficiency, analytical acumen, and a passion for unlocking the value hidden within data.
#show_downloads: true
theme: jekyll-theme-cayman
